

DROP TABLE PRODUCTOPEDIDO IF EXISTS;
CREATE TABLE PRODUCTOPEDIDO (
PRODUCTO_PEDIDOID LONG AUTO_INCREMENT PRIMARY KEY,
PEDIDO_ID INT NOT NULL,
PRODUCTO_ID INT NOT NULL,
CANTIDAD LONG NOT NULL);

DROP TABLE PEDIDOS IF EXISTS;
CREATE TABLE PEDIDOS (
ID_PEDIDO LONG AUTO_INCREMENT PRIMARY KEY,
FECHA LONG NOT NULL,
CANTIDAD_TOTAL INT NOT NULL,
TOTAL DOUBLE NOT NULL);


DROP TABLE CLIENTE IF EXISTS;
DROP SEQUENCE  CLIENTE_SEQ IF EXISTS;
CREATE SEQUENCE  CLIENTE_SEQ AS LONG START WITH 5 INCREMENT BY 1;
CREATE TABLE CLIENTE (
ID_CLIENTE LONG DEFAULT NEXT VALUE FOR CLIENTE_SEQ PRIMARY KEY,
NOMBRE VARCHAR(150) NOT NULL,
APELLIDO VARCHAR(150) NOT NULL, 
DNI LONG NOT NULL
);


DROP TABLE PRODUCTO IF EXISTS;
DROP SEQUENCE  PRODUCTO_SEQ IF EXISTS;
CREATE SEQUENCE  PRODUCTO_SEQ AS LONG START WITH 5 INCREMENT BY 1;
CREATE TABLE PRODUCTO(
ID_PRODUCTO LONG DEFAULT NEXT VALUE FOR PRODUCTO_SEQ PRIMARY KEY,
NOMBRE VARCHAR(150) NOT NULL,
DESCRIPCION VARCHAR(150) NOT NULL,
STOCk LONG NOT NULL, 
PRECIO DOUBLE NOT NULL);



